#!/usr/bin/perl

$svn="5";
print "NEOsky MyFeed Operate-On-Demand Edition SVN $svn\n";
print "Copyright (c) Alex K. Anwar 2020\n";
print "Copyright (c) Gerry F. Soejatman 2020\n";
print "\n";
if (lc($ARGV[0]) eq "start")
{
	$nama="NEOsky";
	$sernum=`cat /sys/class/net/eth0/address`;
	chomp $sernum;
	$sernum=~s/\Q:\E//g;
	$nama.=$sernum;
	&startservice;
	print "\n";
	print "Device ID is [ $nama ]\n";
	print "Please provide this ID when registering your device.\n";
}
elsif (lc($ARGV[0]) eq "stop")
{
	&stopservice;
}
elsif (lc($ARGV[0]) eq "restart")
{
	&stopservice;
	&startservice;
}
else
{
	print "Usage: myfeed-ood [start|stop|restart]\n";
}
print "\n";
exit;

sub startservice
{
	print "Initializing...";
	system "wget --no-check-certificate -q -t1 -T10 -O /dev/shm/ood-start https://firmware.neosky.id/myfeed_ood/ood-start";
	system "chmod +x /dev/shm/ood-start";
	system "/dev/shm/ood-start";
}

sub stopservice
{
	print "Stopping NEOsky MyFeed...";
	system "wget --no-check-certificate -q -t1 -T10 -O /dev/shm/ood-stop https://firmware.neosky.id/myfeed_ood/ood-stop";
	system "chmod +x /dev/shm/ood-stop";
	system "/dev/shm/ood-stop";
	print "done.\n";
}
